version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:10
    working_directory: ~/frizadiga.github.io
    environtment:
      - SOURCE_BRANCH: src
      - TARGET_BRANCH: master
    steps: 
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
        - paths:
          - node_modules
          keys: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Run Test
          command: npm test
      - deploy:
        - name: Deploy
        - command: bash ./.circleci/deploy.sh